name: Llama2
model_name_or_path: meta-llama/Llama-2-7b-chat-hf

config_kwargs:
  trust_remote_code: True

tokenizer_kwargs:
  use_fast: true

defaults:
  - base_hf_llm
  - peft: lora
  - quantization: 4bit
  - _self_
